paths:
  /users/googleIdExists:
    get:
      description: Google Id exists or no?
      tags:
        - Users
      requestBody:
        description: User credentials (googleId)
        content:
          application/json:
            schema:
              type: object
              properties:
                googleId:
                  type: string
      responses:
        200:
          description: Ok